---
- hosts: all
  become: true
  tasks:
    - name: Install knockd on inetRouter
      apt:
        name: knockd
        state: present
      when: ansible_hostname == "inetRouter"

    - name: Configure knockd on inetRouter
      template:
        src: knockd.conf.j2
        dest: /etc/knockd.conf
        owner: root
        group: root
        mode: "0644"
      when: ansible_hostname == "inetRouter"
      notify: Restart knockd

    - name: Enable and start knockd on inetRouter
      systemd:
        name: knockd
        enabled: true
        state: started
      when: ansible_hostname == "inetRouter"

    - name: Install knock client on centralRouter
      apt:
        name: knockd
        state: present
      when: ansible_hostname == "centralRouter"

    - name: Create knock script on centralRouter
      template:
        src: knock_ssh.sh.j2
        dest: /usr/local/bin/knock_ssh.sh
        owner: root
        group: root
        mode: "0755"
      when: ansible_hostname == "centralRouter"

    - name: Disable UFW on inetRouter and inetRouter2
      systemd:
        name: ufw
        state: stopped
        enabled: false
      when: ansible_hostname in ['inetRouter', 'inetRouter2']

    - name: Set up iptables on inetRouter and inetRouter2
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "iptables_rules_{{ ansible_hostname }}.ipv4.j2", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "iptables_restore.j2", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: ansible_hostname in ['inetRouter', 'inetRouter2']

    - name: Install nginx on centralServer
      apt:
        name: nginx
        state: present
      when: ansible_hostname == "centralServer"

    - name: Start nginx on centralServer
      systemd:
        name: nginx
        enabled: true
        state: started
      when: ansible_hostname == "centralServer"

    - name: Enable IP forwarding on routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: ansible_hostname in ['inetRouter', 'inetRouter2', 'centralRouter', 'office1Router', 'office2Router']

    - name: Disable default route on eth0
      template:
        src: "00-installer-config.yaml.j2"
        dest: "/etc/netplan/00-installer-config.yaml"
        owner: root
        group: root
        mode: "0644"
      when: ansible_hostname != "inetRouter"

    - name: Configure static routes
      template:
        src: "50-vagrant_{{ ansible_hostname }}.yaml.j2"
        dest: "/etc/netplan/50-vagrant.yaml"
        owner: root
        group: root
        mode: "0644"

    - name: Apply netplan configuration
      command: netplan apply
      changed_when: true

    - name: Reboot hosts
      reboot:
        reboot_timeout: 600

  handlers:
    - name: Restart knockd
      systemd:
        name: knockd
        state: restarted