---
- hosts: all
  become: true
  tasks:
    - name: Disable UFW on inetRouter
      systemd:
        name: ufw
        state: stopped
        enabled: false
      when: ansible_hostname == "inetRouter"

    - name: Set up NAT on inetRouter
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "iptables_rules.ipv4.j2", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "iptables_restore.j2", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: ansible_hostname == "inetRouter"

    - name: Enable IP forwarding on routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: ansible_hostname in ['inetRouter', 'centralRouter', 'office1Router', 'office2Router']

    - name: Disable default route on eth0
      template:
        src: "00-installer-config.yaml.j2"
        dest: "/etc/netplan/00-installer-config.yaml"
        owner: root
        group: root
        mode: "0644"
      when: ansible_hostname != "inetRouter"

    - name: Configure static routes
      template:
        src: "50-vagrant_{{ ansible_hostname }}.yaml.j2"
        dest: "/etc/netplan/50-vagrant.yaml"
        owner: root
        group: root
        mode: "0644"

    - name: Apply netplan configuration
      command: netplan apply
      changed_when: true

    - name: Reboot hosts
      reboot:
        reboot_timeout: 600